### ISSUE TITLE
Filling a block only shows VASHMARK

### ISSUE THREAD

**Issue by steebchen** [kirbysayshi/vash#104]
When I try to fill a block from a nested layout, I only see this in the code:

```
[VASHMARK-8113110:block-details]
```

Since this is really hard to explain, I ask you too look into [this](https://github.com/yannik-b/AbiFinanzen-17) repository - it's super easy to get started:

```
git clone https://github.com/yannik-b/AbiFinanzen-17 && cd AbiFinanzen-17
npm i
node index.js
```

Then run `xdg-open http://localhost:5000/detail` or open [localhost:5000/detail](http://localhost:5000/detail) in your browser.

**Comment by msdickinson** [comment]
Same issue

**Comment by msdickinson** [comment]
Nm This fixed it.  
fs.readFile('./Views/Home/Index.vash', 'utf8', function (err, data) {

            var tpl = vash.compile(data.toString());
            var rendered = tpl({ X: 'a' }, function sealLayout(err, ctx) {
                response.write(ctx.finishLayout()); // TODO: undocumented
                var out = tpl({ X: 'a' })
                response.end();
            });

           // response.write(out);
         
        });

**Comment by akshay-since1987** [comment]
Request you to close this issue as this is fixed. It shows a lot of open bugs and I am confused as to whether I use this or not
