### ISSUE TITLE
Make an icon for Vash

### ISSUE THREAD

**Issue by dehghani-mehdi** [kirbysayshi/vash#108]
Hi,

I like vash, I sent `add icon request` to `vscode-icons` [an extension of Visual Studio Code](https://github.com/robertohuertasm/vscode-icons/issues/120#issuecomment-236655610), but seems like there is no official icon for Vash, so is possible to add one?

Thanks!

**Comment by kirbysayshi** [comment]
Unfortunately I never got around to making an official icon. Does anyone want to contribute one?
