### ISSUE TITLE
How to make multiple includes for the same component work?

### ISSUE THREAD

**Issue by nishant-chaturvedi** [kirbysayshi/vash#115]
I have noticed, if I try to include the same component multiple times within a block, it only gets rendered once. I am not sure if this is by design or a bug. If it's be design, how can I make something like following work.

I have pagination component, an example :

```
@html.block('pagination', function(model){
    <ul class="pagination pagination-sm pull-right">
        <li><a href="#">1</a></li>
        <li class="active"><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
    </ul>
})
```
Now I want to put it in a page twice, at the top and bottom of a page and to do that I am using, following snippet twice. Surprisingly it gets rendered only once. Please help

```
@html.include('pagination', model)
```

**Comment by kirbysayshi** [comment]
It's been a while since I checked, but I believe `.block` overrides the content each time it is called. You're probably looking for `@html.append` instead of block?

**Comment by kirbysayshi** [comment]
Please reopen if this doesn't help!
