### ISSUE TITLE
vash block error with koa

### ISSUE THREAD

**Issue by mahammad-labib** [kirbysayshi/vash#118]
i have this render error in html page and the block content dosnt shown up
[VASHMARK-3841349:block-body]

**Comment by hooliy** [comment]
我也遇到了同样的问题！

**Comment by kirbysayshi** [comment]
@mahammad-labib  I haven't used koa. How are you registering / using vash with koa? There is a good chance you will need to manually call `finishLayout`, as shown in this comment: https://github.com/kirbysayshi/vash/issues/35#issuecomment-38408041

@hooliy I am sorry, but I cannot speak or read Japanese! Google translate says your comment is roughly "I am disappointed It is the same controversial problem!". I am sorry that you are experiencing the same issue! I hope the above comment helps.

**Comment by hooliy** [comment]
@kirbysayshi Thank you very much for taking time off from your busy schedule to answer my question, but I still hope you can revise the above reply. I am a Chinese, not a japanese.

**Comment by kirbysayshi** [comment]
@hooliy Ack! I am so very sorry for my mistake! Google Translate told me Japanese, but that may have been a residual selection from another time I used Google Translate. I am very sorry for assuming and not double checking. I edited my original comment to correct it, and thank you for correcting me!

**Comment by hooliy** [comment]
@mahammad-labib Hello, have you solved your problem? I have the same problem.

**Comment by kirbysayshi** [comment]
Going to close, but please reopen if there are more details.
