### ISSUE TITLE
<a href="@item.html">...

### ISSUE THREAD

**Issue by fghhfg** [kirbysayshi/vash#122]
**Code**:
```html
<div>
  @model.xxx.forEach(function(item){
    <a href="@item.html">@item</a>
  })
</div>
```

`model.xxx = ['home', 'product', ...]`

**Expected**:
```html
<div>
  <a href="home.html">home</a><a href="product.html">product</a>...
</div>
```

**What I got**:
```html
<div>
  <a href="">home</a><a href="">product</a>...
</div>
```

---
And how do make it newline?

I want my html become:
```html
<div>
  <a href="home.html">home</a>
  <a href="product.html">product</a>
  ...
</div>
```

it is more readable...

**Comment by kirbysayshi** [comment]
The new lines should be kept, not sure why they’re not.

The expression @item.html tells vash to look for an html property on the
item object. You can try either:

@(item + “.html”)
@(item).html

I’m not sure the second will work. The first one with manual concatenation
should though.

**Comment by fghhfg** [comment]
You are so quick!

`@(item + “.html”)` : this one works.
`@(item).html`: this one doesn't work.

thank you.

**Comment by kirbysayshi** [comment]
Thanks for reporting back, and glad to help!
