### ISSUE TITLE
Use syntax highlighting in README.md

### ISSUE THREAD

**Issue by theel0ja** [kirbysayshi/vash#124]
No syntax highlighting in README.md.

https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting

![image](https://user-images.githubusercontent.com/5832930/36344998-ba8bab94-142b-11e8-9fd8-4c5ce44d67b0.png)

**Comment by kirbysayshi** [comment]
If you'd like this and have the time, I'd love a contribution! But unfortunately syntax highlighting is not a high priority for me right now.

If you'd like to continue, feel free to reopen this issue!
