### ISSUE TITLE
Block/append/prepend does not work in @html.include'd files.

### ISSUE THREAD

**Issue by Shedal** [kirbysayshi/vash#16]
**main.js**

``` javascript
var vash = require('vash');
var fs = require('fs');

var pageText = fs.readFileSync('page.vash').toString();
var page = vash.compile(pageText);
console.log(page());
```

**layout.vash**

``` html
<html>
    <head>
        @html.block('scripts')
    </head>
    <body>
        @html.block('content')
    </body>
</html>
```

**page.vash**

``` html
@html.extend('layout.vash', function(model) {
    @html.block('scripts', function() {
        <script>'Page script'</script>
    })

    @html.block('content', function() {
        <div>
            @html.include('component.vash')
        </div>
    })
})
```

**component.vash**

``` html
@html.append('scripts', function() {
    <script>'Component script'</script>
})

<p>Hello!</p>
```

As a result, `<script>'Component script'</script>` does not get rendered.
Why do I need this? Well, I wanted the component to automatically include specific scripts and styles, because I don't want to manually include them on each page where the component is used.
Is this supposed to work? I expected it to.

**Comment by fghhfg** [comment]
Is this normal?

```html
<!DOCTYPE HTML>
<html>

<head>
    [VASHMARK-6193723:block-scripts]
</head>

<body>
    <div>Layout.</div>
    [VASHMARK-3154201:block-content]
</body>

</html>
```


Yes. Here's an example:

layout.main.vash

<!DOCTYPE HTML>
<html>

<head>
    @html.block('scripts')
</head>

<body>
    <div>Layout.</div>
    @html.block('content')
</body>

</html>
news.vash

@html.extend('layout.main.vash', function(model) {

    @html.block('scripts', function() {
        <script>
            console.log('scripts 1');
        </script>
    })


    @html.block('content', function(model) {
        <div>Page.</div>
        @html.include('posts.vash')
    })
})
posts.vash

@html.block('scripts', function() {
    <script>
        console.log('scripts 2');
    </script>
})

<div>Component.</div>
This results in the following output:

<!DOCTYPE HTML>
<html>

<head>
    <script>
        console.log('scripts 2');
    </script>
</head>

<body>
    <div>Layout.</div>
    <div>Page.</div>[VASHMARK-488168:block-scripts]

<div>Component.</div>
</body>

</html>
The indentation gets a little broken as well, by the way. Even if I use .append().
