### ISSUE TITLE
Unmatched BRACE_OPEN error when using ) in blocks

### ISSUE THREAD

**Issue by goloroden** [kirbysayshi/vash#26]
Supposed you have this file as `layout.vash`

```html
<!doctype html>
<html>
  <head>
    <title>dotnetpro-Store</title>
  </head>

  <body>
    @html.block('content')
  </body>
</html>
```

and this file as `index.vash`:

```html
@html.extend('layout', function (model) {
  @html.block('content', function (model) {
    <p>Hello world :-)!</p>
  })
})
```

Then rendering of `index.vash` crashes with the following error message:

> UnmatchedCharacterError: Unmatched BRACE_OPEN at line 1, character 40. Value: {

The problem is the `)` character in the text that shall be printed out. It does not matter whether it's a smiley or something else - as soon as there is a closing brace, the template can not be rendered.

How to solve this?

PS: Of course, a similar problem happens when using the `}` character.

**Comment by kirbysayshi** [comment]
This is fixed as of >= 0.8.0!
