### ISSUE TITLE
Not able to use semicolons for proper JavaScript in blocks

### ISSUE THREAD

**Issue by goloroden** [kirbysayshi/vash#27]
Supposed I have the following file `index.vash`:

```html
@html.extend('layout', function (model) {
  @html.block('content', function (model) {
    <p>Hallo Welt!</p>
  })
})
````

Then the code is "broken" due to missing semicolons at the end of the two lines containing the `})` characters. But if I add them I won't get the result I'd like to, as they are sent to the client instead.

How to fix this?

**Comment by kirbysayshi** [comment]
I've been thinking about this some more, and I think it's actually impossible for vash to know when a trailing semicolon is meant to be code or content. However, you can force the semicolons to be parsed as code by wrapping the layout calls in an anonymous code "block":

```html
@{
  html.extend('layout', function (model) {
    @html.block('content', function (model) {
      <p>Hallo Welt!</p>
    });
  });
}
```

Going to close this for now, as the case of `@something.hey(function() { return 'yo' });` (semicolon should be content) is ambiguously close to `@html.block('layout', function() {});` (semicolon should be code).
