### ISSUE TITLE
Error "has no method forEach" when receiving JSON array back from REST service

### ISSUE THREAD

**Issue by weagle08** [kirbysayshi/vash#42]
I have a simple REST service that sends back a JSON object of preferences and when I try to render these with the following code it fails with "Object has no method 'forEach'".

******_SENDING THE REQUEST**_*****
var getReq = http.get('http://localhost:8081/prefs', fuction(response){
&nbsp;&nbsp;response.on('data', function(data){
&nbsp;&nbsp;&nbsp;&nbsp;console.log(data);  //AT THIS LINE DATA PRINTS OUT AS A BUFFER OF INTS
&nbsp;&nbsp;&nbsp;&nbsp;res.render('preferences', {title : 'Preferences', prefs : data});
&nbsp;&nbsp;});
});

******************_THE VIEW (preferences.vash)**_*************
@html.extend('layout', function(model){
&nbsp;&nbsp;@html.block('body', function(model){
&nbsp;&nbsp;&nbsp;&nbsp;@model.prefs.forEach(function(pref){              <----THIS LINE THROWS THE ERROR
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div&gt;@pref.name&lt;/div&gt;
&nbsp;&nbsp;&nbsp;&nbsp;})
&nbsp;&nbsp;})
})

****************_RETURNED JSON OBJ**_************
[{
    'name' : 'blah1'
}, {
    'name' : 'blah2'
}, {
    'name' : 'blah3'
}]

I am new to node and javascript in general so maybe this is not a bug but an error on my part. If so could someone please explain the issue?

**Comment by xgqfrms-GitHub** [comment]
what's wrong with this ? Any body can help?
![jquery-error](https://cloud.githubusercontent.com/assets/18028768/18745680/bc09168e-80f5-11e6-8fd2-76b29e393f78.PNG)
