### ISSUE TITLE
Equals signs are lost in attribute values

### ISSUE THREAD

**Issue by meandmycode** [kirbysayshi/vash#61]
Given the following vash template:

```html
<meta name="viewport" content="width=device-width, initial-scale=1">
```

The expected result should be the same as the source, however in 0.8 the result is instead:

```html
<meta name="viewport" content="widthdevice-width, initial-scale1">
```

Where the equal signs are lost within the value, does not seem to matter about the attribute name nor the tag name.

Thanks,

**Comment by kirbysayshi** [comment]
Thanks so much for reporting, and thanks for the great test case! This has been fixed and released as v0.8.1.
