### ISSUE TITLE
Feature: nesting extend and redefining blocks

### ISSUE THREAD

**Issue by meandmycode** [kirbysayshi/vash#63]
I remember having a look into the pre 0.8 source regarding this and had come to the conclusion that the feature probably wouldn't be possible as it conflicted with includes, however I may have been wrong regarding this.

Back in pre 0.8 I believe the result of trying to nest extend was that Vash would render VASHMARK markers into the resulting html, this doesn't appear to be the case in 0.8, although I may not be recreating the same conditions.

Essentially this feature comes down to the following supported razor structure:

```html
# layout.vash
@html.block("content")
```

```html
# page-layout.vash
@html.extend("layout.vash", function() {
  @html.block("content", function() {
    <h1>before</h1>
    @html.block("content")
    <h1>after</h1>
  })
})
```

Then given the following renderable templates:

```html
@html.extend("layout.vash", function() {
  @html.block("content", function() {
    <p>content</p>
  })
})
```

Would render HTML:

```html
<p>content</p>
```

```html
@html.extend("page-layout.vash", function() {
  @html.block("content", function() {
    <p>content</p>
  })
})
```

Would render HTML:

```html
<h1>before</h1>
<p>content</p>
<h1>after</h1>
```

This may not be easy to do, or even not something Vash wants to support can be useful.

Thanks,

**Comment by kirbysayshi** [comment]
Very interesting... that's definitely not something I thought was possible. The layout helpers haven't changed in 0.8.0, and I just ran the following code to test this out. Still got vashmarks in there:

```js
var vash = require('vash');
vash.helpers.config.browser = true;

vash.install('layout.vash', '@html.block("content")');
vash.install('page-layout.vash', ''
  + '@html.extend("layout.vash", function() {'
  + '  @html.block("content", function() {'
  + '    <h1>before</h1>'
  + '    @html.block("content")'
  + '    <h1>after</h1>'
  + '  })'
  + '})'
)

var tpl = vash.compile(''
	+ '@html.extend("layout.vash", function() {'
  + '  @html.block("content", function() {'
  + '    <p>content</p>'
  + '  })'
  + '})'
);

console.log(tpl());
```

If you want to take a shot at implementing it, please try! Otherwise I probably won't until I decide to rewrite the layout system to resolve things statically (right now it's all at runtime).

**Comment by meandmycode** [comment]
Thanks for the feedback, I will certainly give it another look and submit a PR if I make progress there.

**Comment by kirbysayshi** [comment]
Please do! And if you have questions about how something works internally don't hesitate to ask.

**Comment by fghhfg** [comment]
@kirbysayshi  your code:
```js
var vash = require('vash');
vash.helpers.config.browser = true;

vash.install('layout.vash', '@html.block("content")');
vash.install('page-layout.vash', ''
  + '@html.extend("layout.vash", function() {'
  + '  @html.block("content", function() {'
  + '    <h1>before</h1>'
  + '    @html.block("content")'
  + '    <h1>after</h1>'
  + '  })'
  + '})'
)

var tpl = vash.compile(''
  + '@html.extend("layout.vash", function() {'
  + '  @html.block("content", function() {'
  + '    <p>content</p>'
  + '  })'
  + '})'
);

console.log(tpl());
```

output:
```
[VASHMARK-8006748:block-content]
```
