### ISSUE TITLE
Compiler hangs for some templates

### ISSUE THREAD

**Issue by mpwalkerdine** [kirbysayshi/vash#68]
These all work fine:

```bash
printf "@:Some Text\n" | vash -t test -p test
printf "@html.block('test')\n" | vash -t test -p test
printf "@html.block('test')\n@:Some Text\n" | vash -t test -p test
printf "<div>\nSome Text\n</div>\n@html.block('test')\n" | vash -t test -p test
```

But this one hangs:
```bash
printf "@:Some Text\n@html.block('test')\n" | vash -t test -p test
```

I've tracked it down to `exports.compile` in  `index.js`, line 62:
`while(more !== null) more = p.read();`

`more` becomes `undefined` and it loops forever.

**Comment by kirbysayshi** [comment]
@mpwalkerdine I took a look at this today, and released a fix as v0.8.6! But in my tests, the problem was actually an unhandled parser state, not the `more !== null` as you stated. There may be two bugs at work here. Do you mind retesting, and see if your actual template still exhibits the problem? If it does, please reopen this issue!

**Comment by kirbysayshi** [comment]
Also thanks for the investigation and bug report!

**Comment by mpwalkerdine** [comment]
@kirbysayshi Thanks, happy to help. I'll double check after work. I didn't mean to suggest the root cause was the `more !== null`, just that's as far down as I'd got into looking. It seems plausible that an unhandled parser state would cause `more = p.read()` to be undefined.

**Comment by kirbysayshi** [comment]
Oh definitely! I didn't say that to chastise, just to explain why there
could be more than a single bug responsible. I'm so grateful that you dug
deep enough to give a great report!

Yip yip,
~ Drew*

**Comment by mpwalkerdine** [comment]
No offence taken, just explaining my evidently ambiguous statement. Hopefully it didn't cause too much of a wild goose chase... :innocent: 

Anyway, this seems fully fixed from my perspective. Nice work, and thanks for the great template engine!
