### ISSUE TITLE
Error from parser if vash files contains html tag with '-' character (like <accordion-group>)

### ISSUE THREAD

**Issue by olivierValence** [kirbysayshi/vash#71]
Hi,

I have got an error when your parser encounter a tag with a '-' (like accordion-group from https://angular-ui.github.io/bootstrap/) in a vash file.

I locally correct this error by updating the IDENTIFIER regex in token.js. I add the '-' character in the second group => 'IDENTIFIER', (/^([_$a-zA-Z\xA0-\uFFFF][\-_$a-zA-Z0-9\xA0-\uFFFF]*)/).
Is it a good update ?

Thanks for your work. Olivier

**Comment by kirbysayshi** [comment]
published as v0.8.4!

Thanks for the bug report. The problem was actually in the parser, which was checking for likely valid tag names. It should work now!

**Comment by olivierValence** [comment]
your update fix the error. 
Thanks a lot
