### ISSUE TITLE
Created NuGet package

### ISSUE THREAD

**Issue by sonnylegreat** [kirbysayshi/vash#75]
Hi There, I'm using your project in an ASP.NET application so I made a NuGet package for it. Hope that's okay.

https://www.nuget.org/packages/Vash/

Also your documentation doesn't appear to match your most recent release build.
Thanks.

**Comment by kirbysayshi** [comment]
Thanks for making a package, if that helps people use Vash more easily I'm all for it.

Could you be more specific on what is out of date with the documentation?

**Comment by sonnylegreat** [comment]
It's actually really nothing looking back. It's just that the example you use in the Browser- Vanilla part of your documentation imports a minified file as the example, but there is no vash.min.js in your latest release.

**Comment by kirbysayshi** [comment]
Thanks! I updated the readme with the proper path.
