### ISSUE TITLE
Wrong output in documentation

### ISSUE THREAD

**Issue by steebchen** [kirbysayshi/vash#81]
In this section https://github.com/kirbysayshi/vash#explicit-markup- the output is wrong:

input:

    // model = ['a']
    @model.forEach(function(item){
        @: item
    })
output:

    a

But the output should be:

    item

Maybe you can extend this example like this:
    // model = ['foo', 'bar']
    @model.forEach(function(item){
        @: item: @item <br/>    
    })

output:
    item: foo
    item: bar

**Comment by kirbysayshi** [comment]
Thanks for the report! You were totally right, not sure what I was trying to demonstrate with that example. Should be fixed now!
