### ISSUE TITLE
Having a new line after the 'else' keyword fails to recognise else block

### ISSUE THREAD

**Issue by ichpuchtli** [kirbysayshi/vash#82]
```
@if(true)
{
     <strong>Hello</strong>
}
else
{
     <strong>World!</strong>
}
```
Outputs:

**Hello**  else { **World!** }

**Comment by kirbysayshi** [comment]
Definitely a bug, I'll try to get to this tonight.

**Comment by kirbysayshi** [comment]
Hey @ichpuchtli, I just tried reproducing this, and could not. What version of vash are you using?

**Comment by ichpuchtli** [comment]
I've been able to reproduce it in this jsfiddle. 

https://jsfiddle.net/jvvc7od2/1/

I've just copied 0.9.2 into the javascript section with the compile code below that.

**Comment by ichpuchtli** [comment]
If you collapse the ```else``` state back so it's ```} else {``` it works fine.

**Comment by kirbysayshi** [comment]
Thanks for the test case! The problem was more due to the combination of whitespace (the indent) + newline. This fix is published as v0.9.3!

**Comment by ichpuchtli** [comment]
+1 fastest bug fix ever. Keep up the good work.

**Comment by kirbysayshi** [comment]
Thanks! Sorry it was a bug at all :S
