### ISSUE TITLE
if-else not working

### ISSUE THREAD

**Issue by chadcampbell** [kirbysayshi/vash#91]
Hello,

I've been experimenting with Vash and I've learned that the if-else block is not working properly. For example, if I have the following:

```
<!DOCTYPE html>
<html lang="en">
@{ 
  model = { theme: 'jungle' };
}
	<head>
	    <title>Hello World</title>    
   	   @html.block('head')
	</head>

	<body>
        @if (model.theme === 'jungle') {
            <h1>Jungle Theme</h1>    
        } else if (model.theme === 'roman') {
            <h1>Roman Theme</h1>
        } else { 
            <h1>Other Theme</h1>
        }  
        @html.block('content')                
    </body>
</html>
```

The view will be rendered as:

# Jungle theme
## Content
# Other Theme

However, I was expecting the following to get rendered:

# Jungle theme
## Content

Oddly, if I change the code so that the final `else` block uses an `else-if` the blocks get rendered out-of-order. For example:

```
<!DOCTYPE html>
<html lang="en">
@{ 
  model = { };
}
	<head>
	    <title>Hello World</title>    
   	   @html.block('head')
	</head>

	<body>
        @if (model.theme === 'jungle') {
            <h1>Jungle Theme</h1>    
        } else if (model.theme === 'roman') {
            <h1>Roman Theme</h1>
        } else if (!model.theme) { 
            <h1>Other Theme</h1>
        }  
        @html.block('content')                
    </body>
</html>
```

Renders as:

## Content
# Other Theme

**Comment by kirbysayshi** [comment]
This was an excellent bug report, thank you so much for being so clear! This should now be fixed in v0.9.4. Thanks for using vash!
