### ISSUE TITLE
Auto minimize vash templates?

### ISSUE THREAD

**Issue by steebchen** [kirbysayshi/vash#94]
Is there a way I can minify the vash files with a middleware when they are send to the browser?

**Comment by kirbysayshi** [comment]
Sure, but it depends on how you're sending your templates to the browser. I'd like to offer guidance, but it's extremely difficult without knowing more about how you're shipping templates.

Generally you want to build all of your templates up into a single file, and send that to the browser. What kind of usage are you envisioning via middleware? Could you provide an example?

**Comment by kirbysayshi** [comment]
Hey @steebchen, if this is still an issue for you, please add some more details and reopen!
